development:
  adapter: postgresql
  encoding: utf8
  database: deliveryangels_dev
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: deliveryangels_test
  pool: 5
  username:
  password:
